### ISSUE TITLE
Migrate repo from "website" to "meta-paleo.github.io"

### ISSUE THREAD

**Issue by RaoOfPhysics** [Meta-Paleo/meta-paleo.github.io#2]
See "User and Organization Pages sites" section here: https://help.github.com/articles/user-organization-and-project-pages/

This would allow you to use the URL https://meta-paleo.github.io without the `Website` bit at the end.

As simple as renaming the repo and changing the settings.

**Comment by Protohedgehog** [comment]
That totally worked, thank you Achintya!! :) https://meta-paleo.github.io/

**Comment by RaoOfPhysics** [comment]
Yay! :D
