### ISSUE TITLE
Migrate individual pages to respective directories

### ISSUE THREAD

**Issue by RaoOfPhysics** [Meta-Paleo/meta-paleo.github.io#3]
I'm guessing this website is made with `blogdown`, so I'm not sure how easy it is to use "clean" URLs in the top menu, but you might want to consider moving your individual pages to their own directories and renaming the files `index.Rmd` in each directory. That way, instead of visiting, say, `https://meta-paleo.github.io/[Website/]about.html`, you could point people to `https://meta-paleo.github.io/[Website/]about/`.

So, your directory structure would be:

```
project/
│   README.md
│   README.html
│   […]
│   index.Rmd
│   index.html
│
└───about/
│   │   index.Rmd
│   │   Index.html
│   
└───OpenPaleo
    │   index.Rmd
    │   index.html
│
└───[…]/
```

Related to #2, I think.

**Comment by Protohedgehog** [comment]
Fixed via the linked issue :)

**Comment by Protohedgehog** [comment]
Ah so just without the .html bits at the end, you mean..? :)

**Comment by RaoOfPhysics** [comment]
Yes. I tried to do it with RMarkdown but it didn't work immediately. Can investigate if you think it would help.
